---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  require_chef: false
  formula: elasticsearch
  dependencies:
    - name: sun-java
      path: vendor/sun-java-formula
  state_top:
    base:
      '*':
        - sun-java
        - sun-java.env
        - elasticsearch
  pillars:
    top.sls:
      base:
        "*":
          - elasticsearch

platforms:
  - name: ubuntu-16.04
    driver_config:
      provision_command:
        - apt-get update && apt-get install -y locales && locale-gen en_US.UTF-8
      run_command: /sbin/init

suites:
  - name: elasticsearch_server 
    provisioner:
     pillars-from-files:
        elasticsearch.sls: test/pillar/elasticsearch.sls
  - name: elasticsearch_server_curator 
    provisioner:
     pillars-from-files:
        elasticsearch.sls: test/pillar/curator.sls

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE
