---
driver:
  name: docker
  use_sudo: false
  privileged: true
  provision_command:
    - locale-gen en_US.UTF-8
    - apt-get update                                 # base image is out of date
    - apt-get install -y software-properties-common  # required for add-apt-repository
    - add-apt-repository -y ppa:openjdk-r/ppa
    - apt-get update
    - apt-get install -y openjdk-8-jre-headless
    - update-ca-certificates -f

provisioner:
  name: salt_solo
  require_chef: false
  formula: elasticsearch
  state_top:
    base:
      '*':
        - elasticsearch

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
    driver_config:
      run_command: /sbin/init

suites:
  - name: default
  - name: with-pillar-set
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - elasticsearch
        elasticsearch.sls:
          elasticsearch:
            config:
              network.host: 0.0.0.0
            plugins:
              lang-python: lang-python
  - name: version-5.0-with-pillar-set
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - elasticsearch
        elasticsearch.sls:
          elasticsearch:
            major_version: 5
            config:
              network.host: 0.0.0.0
            plugins:
              lang-python: lang-python
  - name: version-5.0
    excludes:
      - ubuntu-14.04
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - elasticsearch
        elasticsearch.sls:
          elasticsearch:
            major_version: 5

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE
