---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  require_chef: false
  formula: elasticsearch
  dependencies:
    - name: sun-java
      path: vendor/sun-java-formula
  state_top:
    base:
      '*':
        - sun-java
        - sun-java.env
        - elasticsearch

platforms:
  - name: ubuntu-14.04
    driver_config:
      provision_command:
        - locale-gen en_US.UTF-8
  - name: ubuntu-16.04
    driver_config:
      provision_command:
        - locale-gen en_US.UTF-8
      run_command: /sbin/init

suites:
  - name: default
  - name: with-pillar-set
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - elasticsearch
        elasticsearch.sls:
          elasticsearch:
            config:
              network.host: 0.0.0.0
            plugins:
              lang-python: lang-python
  - name: version-5.0
    excludes:
      - ubuntu-14.04
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - elasticsearch
        elasticsearch.sls:
          elasticsearch:
            major_version: 5
            plugins:
              lang-python: lang-python
            jvm_opts:
              - -Xms2g
              - -Xmx2g
              - -XX:+UseConcMarkSweepGC
              - -XX:CMSInitiatingOccupancyFraction=75
              - -XX:+UseCMSInitiatingOccupancyOnly
              - -XX:+DisableExplicitGC
              - -XX:+AlwaysPreTouch
              - -server
              - -Xss1m
              - -Djava.awt.headless=true
              - -Dfile.encoding=UTF-8
              - -Djna.nosys=true
              - -Djdk.io.permissionsUseCanonicalPath=true
              - -Dio.netty.noUnsafe=true
              - -Dio.netty.noKeySetOptimization=true
              - -Dio.netty.recycler.maxCapacityPerThread=0
              - -Dlog4j.shutdownHookEnabled=false
              - -Dlog4j2.disable.jmx=true
              - -Dlog4j.skipJansi=true
              - -XX:+HeapDumpOnOutOfMemoryError

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE
