---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  require_chef: false
  formula: elasticsearch
  dependencies:
    - name: sun-java
      path: vendor/sun-java-formula
  state_top:
    base:
      '*':
        - sun-java
        - sun-java.env
        - elasticsearch

platforms:
  - name: ubuntu-14.04
    driver_config:
      provision_command:
        - locale-gen en_US.UTF-8
  - name: ubuntu-16.04
    driver_config:
      provision_command:
        - apt-get update && apt-get install -y locales && locale-gen en_US.UTF-8
      run_command: /sbin/init

suites:
  - name: default
  - name: with-pillar-set
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - elasticsearch
        elasticsearch.sls:
          elasticsearch:
            config:
              network.host: 0.0.0.0
            plugins:
              lang-python: lang-python
  - name: version-5.0
    excludes:
      - ubuntu-14.04
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - elasticsearch
        elasticsearch.sls:
          elasticsearch:
            version: 5.*
            plugins:
              lang-python: lang-python
            jvm_opts:
              - '# Test String'

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE
