---
driver:
  name: docker
  use_sudo: false
  provision_command: apt-get install -y openjdk-7-jre-headless

provisioner:
  name: salt_solo
  require_chef: false
  formula: elasticsearch
  state_top:
    base:
      '*':
        - elasticsearch

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
  - name: config-pillar-set
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - elasticsearch
        elasticsearch.sls:
          elasticsearch:
            config:
              network.host: 0.0.0.0

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE
