---
driver:
  name: docker
  use_sudo: false
  provision_command: apt-get install -y openjdk-7-jre-headless

provisioner:
  name: salt_solo
  require_chef: false
  formula: elasticsearch
  state_top:
    base:
      '*':
        - elasticsearch

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
  - name: config-pillar-set
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - elasticsearch
        elasticsearch.sls:
          elasticsearch:
            config:
              network.host: 0.0.0.0
  - name: version-5.0
    driver_config:
      provision_command:
        - apt-get update  # base image is out of date
        - apt-get install -y software-properties-common  # required for add-apt-repository
        - add-apt-repository -y ppa:openjdk-r/ppa
        - apt-get update
        - apt-get install -y openjdk-8-jre-headless
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - elasticsearch
        elasticsearch.sls:
          elasticsearch:
            major_version: 5

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE
